# Generated by Django 5.0.6 on 2024-06-11 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='desc',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
