# Generated by Django 5.0.6 on 2024-06-14 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_liked_anime_user_likedanime_anime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_likedanime',
            name='date_liked',
            field=models.DateField(auto_now_add=True),
        ),
    ]
