# Generated by Django 5.0.7 on 2024-07-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_likedanime_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=models.TextField(),
        ),
    ]
