# Generated by Django 5.0.7 on 2024-07-18 04:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_anime_genres_alter_anime_studios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='genres',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=35), size=None),
        ),
        migrations.AlterField(
            model_name='anime',
            name='studios',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=60), size=None),
        ),
    ]
