# Generated by Django 5.0.7 on 2024-07-19 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_user_likedanime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_likedanime',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
