# Generated by Django 5.0.7 on 2024-09-18 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_user_likedanime_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
